name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-23.10]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          git-core \
          libairspy-dev \
          libopencv-dev \
          libproj-dev \
          librtlsdr-dev \
          zlib1g-dev

    - name: Build goestools
      run: |
        git submodule init
        git submodule update --recursive
        mkdir -p build
        cd build
        cmake ../ -DCMAKE_INSTALL_PREFIX=/usr/local
        make -j4
        sudo make install
